baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo + Stork'

disableKinds = ['RSS','sitemap','taxonomy','term']

[outputFormats.stork]
mediaType = 'application/json'
baseName = 'stork.config'
isPlainText = true

[outputs]
home = ['html','stork']
